djangoapp/apps/calculos/urls.py
from django.urls import path

from apps.calculos.views.delecao import DelCalculos
from apps.calculos.views.importacao import UploadPjeCalc
from apps.calculos.views.listagem import ListCalculos
from apps.calculos.views.verbas import ListVerbas
from apps.calculos.views.verbas_detalhes import ListVerbasDetalhes
from apps.calculos.views.relatorio import RelCalculos



urlpatterns = [
    path('pjecalc_upload', UploadPjeCalc.as_view(), name='pjecalc_upload'),

    path('listagem_calculos', ListCalculos.as_view(), name='listagem_calculos'),
    path('listagem_calculos/<int:processo_id>', ListCalculos.as_view(), name='listagem_calculos'),

    path('delete_calculos/', DelCalculos.as_view(), name='delete_calculos'),
    path('delete_calculos/<int:pk>', DelCalculos.as_view(), name='delete_calculos'),

    path('listagem_verbas', ListVerbas.as_view(), name='listagem_verbas'),
    path('listagem_verbas/<int:calculo_id>', ListVerbas.as_view(), name='listagem_verbas'),

    path('listagem_verbas_detalhes', ListVerbasDetalhes.as_view(), name='listagem_verbas_detalhes'),
    path('listagem_verbas_detalhes/<int:verba_id>', ListVerbasDetalhes.as_view(), name='listagem_verbas_detalhes'),

    path('relatorio_calculos', RelCalculos.as_view(), name='relatorio_calculos'),
]

djangoapp/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.home.urls')),
    path('acesso/', include('apps.acesso.urls')),
    path('calculos/', include('apps.calculos.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('processos/', include('apps.processos.urls')),
    path('servicos/', include('apps.servicos.urls')),

    #  Libs
    re_path(r"^celery-progress/", include("celery_progress.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/apps/calculos/models.py
from django.db import models
from apps.processos.models import Processos


class Calculos(models.Model):

    processo = models.ForeignKey(
        Processos, verbose_name="Nº Processo", on_delete=models.CASCADE
    )
    dt_inicio_calc = models.DateField(
        "D.Inicio", auto_now=False, auto_now_add=False)
    dt_fim_calc = models.DateField(
        "D.Fim", auto_now=False, auto_now_add=False)
    dt_liquidacao = models.DateField(
        "D.Liquidação", auto_now=False, auto_now_add=False)
    dt_criacao = models.DateField(
        "D.Criação", auto_now=True)
    n_arquivo = models.CharField("Nome do aquivo", max_length=200)
    n_pje = models.IntegerField("N.Cálculo")
    per_parcelas_rt = models.FloatField("% Parcelas Remuneratórias e Tributáveis")
    

    class Meta:
        verbose_name = "Cálculo"
        verbose_name_plural = "Cálculos"

    def __str__(self):
        return self.processo.n_processo
    
    @property
    def total_devido(self):
        return self.verbascalc_set.get(descricao='Total').v_devido
    
    @property
    def total_pago(self):
        return self.verbascalc_set.get(descricao='Total').v_pago
    
    @property
    def total_calculado(self):
        return self.verbascalc_set.get(descricao='Total').v_calculado
    
    @property
    def total_juros(self):
        return self.verbascalc_set.get(descricao='Total').juros
    
    @property
    def total_corrigido(self):
        return self.verbascalc_set.get(descricao='Total').v_corrigido
    
    @property
    def total(self):
        return self.verbascalc_set.get(descricao='Total').total
    
    @property
    def get_dt_liquidacao(self):
        from datetime import datetime
        return datetime.strftime(self.dt_liquidacao, "%d/%m/%Y")
    
    @property
    def reclamada(self):
        return self.processo.reclamada.nome
    
    @property
    def reclamante(self):
        return self.processo.reclamante.nome
    
    @property
    def get_processo(self):
        return self.processo.n_processo
    
    def get_coluna(self, descricao):
        verba = self.verbascalc_set.filter(descricao=descricao)
        return verba[0].total if verba else ""


class VerbasCalc(models.Model):

    calculo = models.ForeignKey(Calculos, verbose_name = "Cálculo", on_delete=models.CASCADE)
    descricao = models.CharField("Descrição", max_length=200)
    v_devido = models.FloatField("Valor Devido", null=True, blank=True)
    v_pago = models.FloatField("Valor Pago", null=True, blank=True)
    v_calculado = models.FloatField("Valor Calculado", null=True, blank=True)
    v_corrigido = models.FloatField("Valor Corrigido")
    juros = models.FloatField("Juros")
    total = models.FloatField("Total")
    
    comentario = models.CharField("Comentário", max_length=200, blank=True, null=True)
    insidencia = models.CharField("Incidência(s)", max_length=200, blank=True, null=True)

    class Meta:
        verbose_name = "Verba"
        verbose_name_plural = "Verbas"

    def __str__(self):
        return self.descricao
    
    
class VerbasCalcDetalhes(models.Model):

    verba = models.ForeignKey(VerbasCalc, verbose_name = "Verba", on_delete=models.CASCADE)
    data = models.DateField('Período Mensal', auto_now=False)
    base = models.FloatField('Base', null=True, blank=True)
    divisor = models.FloatField('Divisor', null=True, blank=True)
    multiplicador = models.FloatField('Multiplicador', null=True, blank=True)
    quantidade = models.FloatField('Quantidade', null=True, blank=True)
    dobra = models.BooleanField('Dobra', default=False)
    devido = models.FloatField('Devido')
    pago = models.FloatField('Pago')
    diferenca = models.FloatField('Diferença')
    icm = models.FloatField('Índice Correção')
    v_corrigido = models.FloatField('Valor Corrigido')

    class Meta:
        verbose_name = "Detalhe de Verba"
        verbose_name_plural = "Detalhes de Verbas"

    def __str__(self):
        return self.verba
    

class DebitosReclamado(models.Model):

    calculo = models.ForeignKey(Calculos, verbose_name = "Cálculo", on_delete=models.CASCADE)
    descricao = models.CharField("Descrição", max_length=200)
    valor = models.FloatField("Valor")

    class Meta:
        verbose_name = "Debito"
        verbose_name_plural = "Debitos"

    def __str__(self):
        return self.descricao


class CredDesReclamante(models.Model):

    calculo = models.ForeignKey(Calculos, verbose_name = "Cálculo", on_delete=models.CASCADE)
    descricao = models.CharField("Descrição", max_length=200)
    valor = models.FloatField("Valor")

    class Meta:
        verbose_name = "Crédito e Desconto de Reclamante"
        verbose_name_plural = "Créditos e Descontos de Reclamante"

    def __str__(self):
        return self.descricao

djangoapp/apps/calculos/views/delecao.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.urls import reverse
from django.views.generic import DeleteView
from django.contrib import messages

from apps.calculos.models import Calculos


class DelCalculos(DeleteView):
    model = Calculos
    
    def get_success_url(self):
        return reverse('listagem_calculos')

    def form_invalid(self, form):
        messages.error(self.request, "Erro na Deleção do Cálculo. {}".format(form.errors))
        return super().form_invalid(form)
        
    def form_valid(self, form):
        messages.success(self.request, "Cálculo Deletado com sucesso")
        return super().form_valid(form)

djangoapp/apps/calculos/views/importacao.py
from django.conf import settings
from django.contrib import messages
from django.core.files.storage import default_storage
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView

from apps.utils.celery.base import CeleryTaskMixin
from apps.calculos.tasks import import_pjecalc_task
# Create your views here.


class UploadPjeCalc(TemplateView, CeleryTaskMixin):

    template_name='calculos/upload_pjecalc.html'
    task_result = None
        
        
    def get_url_return(self):
        return reverse('pjecalc_upload')
       
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumbs'] = [
            {
                'title': 'Home',
                'url': 'home',
                'activate': None
            },{
                'title': 'Cálculo',
                'url': '',
                'activate': None
            },{
                'title': 'Upload - PJE-Calc',
                'url': '',
                'activate': 'true'
            }
        ]
        context['title'] = 'Upload'
        context['card_title'] = 'PJE-Calc'
        context['subtitle'] = 'Aqui você faz o upload de arquivos em PDF, originados do PJE-Calc, que teram os valores do resumo salvos no banco de dados.'
        
        return context
    
    def salvar_temporarios(self, file):
        # Salve o arquivo temporariamente
        nome_arq = '{}/tmp/{}'.format(
            settings.MEDIA_ROOT,
            file.name
        )
        with default_storage.open(nome_arq, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)
        return destination.name
    
    def post(self, request, *args, **kwargs):
        files = self.request.FILES.getlist('arquivo')
        temporarios = []
        for file in files:
            nome_arq = self.salvar_temporarios(file)
            temporarios.append(nome_arq)

        self.task_result = import_pjecalc_task.apply_async(
            kwargs={'dados':temporarios}
        )

        return render(self.request, self.progressbar_template_name, self.set_task_params)

djangoapp/apps/calculos/views/listagem.py
from django.views.generic import ListView

from apps.calculos.models import Calculos
from apps.processos.models import Processos
# Create your views here.


class ListCalculos(ListView):
    template_name='calculos/listagem.html'
    model = Calculos

    def get_title(self):
        complemento = ''
        if 'processo_id' in self.kwargs:
            processo = Processos.objects.get(id=self.kwargs['processo_id'])
            complemento = ' do Processo nº {}'.format(processo)
        return 'Calculos' + complemento

    def get_queryset(self):
        if 'processo_id' in self.kwargs:
            self.queryset = self.model.objects.filter(processo_id=self.kwargs['processo_id'])
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumbs'] = [
            {
                'title': 'Home',
                'url': 'home',
                'activate': None
            },{
                'title': 'Processo',
                'url': 'listagem_processos',
                'activate': None
            },{
                'title': 'Calculo',
                'url': '',
                'activate': 'true'
            }
        ]

        if 'processo_id' in self.kwargs:
            context['processo'] = Processos.objects.get(id=self.kwargs['processo_id'])

        context['title'] = self.get_title()
        context['card_title'] = 'Listagem'
        context['subtitle'] = 'Aqui você tem a lista de todos os calculos cadastrados.'
        
        return context

djangoapp/apps/calculos/views/relatorio.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView

from apps.calculos.mixins.relatorio import RelatorioMixin
from apps.calculos.models import Calculos
# Create your views here.


class RelCalculos(ListView, RelatorioMixin):
    template_name='calculos/relatorio.html'
    model = Calculos

    def get_title(self):
        return 'Relatório de Calculos'

    def get_queryset(self):
        if 'processo' in self.request.GET and self.request.GET['processo']:
            self.kwargs['processo__id'] = self.request.GET['processo']
        if 'reclamante' in self.request.GET and self.request.GET['reclamante']:
            self.kwargs['processo__reclamante__id'] = self.request.GET['reclamante']
        if 'reclamada' in self.request.GET and self.request.GET['reclamada']:
            self.kwargs['processo__reclamada__id'] = self.request.GET['reclamada']
        self.queryset = self.model.objects.filter(**self.kwargs)
        return super().get_queryset()
    
    def get(self, request, *args, **kwargs):
        if 'submit' in request.GET and request.GET['submit'] == 'exportar':
            self.object_list = self.get_queryset()
            context = super().get_context_data(**kwargs)
            context = self.get_relatorio(context)
            return self.get_export(context)
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumbs'] = [
            {
                'title': 'Home',
                'url': 'home',
                'activate': None
            },{
                'title': 'Calculos',
                'url': '',
                'activate': None
            },{
                'title': 'Relatório',
                'url': '',
                'activate': 'true'
            }
        ]
        context = self.get_relatorio(context)
        return context

djangoapp/apps/calculos/views/verbas.py
from django.views.generic import ListView

from apps.calculos.models import Calculos, VerbasCalc
# Create your views here.


class ListVerbas(ListView):
    template_name='calculos/listagem_verbas.html'
    model = VerbasCalc

    def get_title(self):
        calculo = Calculos.objects.get(id=self.kwargs['calculo_id'])
        return 'Resumo do Calculo nº {} do Processo {}.'.format(calculo.id, calculo.processo)

    def get_queryset(self):
        self.queryset = self.model.objects.filter(calculo_id=self.kwargs['calculo_id'])
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumbs'] = [
            {
                'title': 'Home',
                'url': 'home',
                'activate': None
            },{
                'title': 'Calculo',
                'url': '',
                'activate': None
            },{
                'title': 'Resumo',
                'url': '',
                'activate': 'true'
            }
        ]
        context['calculo'] = Calculos.objects.get(id=self.kwargs['calculo_id'])    
        context['title'] = self.get_title()
        context['card_title'] = 'Listagem'
        context['subtitle'] = 'Aqui você tem a lista de todos as verbas cadastrados.'
        
        return context

djangoapp/apps/calculos/views/verbas_detalhes.py
from django.views.generic import ListView

from apps.calculos.models import  VerbasCalc, VerbasCalcDetalhes
# Create your views here.


class ListVerbasDetalhes(ListView):
    template_name='calculos/listagem_verbas_detalhes.html'
    model = VerbasCalcDetalhes

    def get_title(self):
        verba = VerbasCalc.objects.get(id=self.kwargs['verba_id'])
        return 'Processo {} - Calculo nº {} - Detalhes - {}'.format(verba.calculo.processo, verba.calculo.id, verba )

    def get_queryset(self):
        self.queryset = self.model.objects.filter(verba_id=self.kwargs['verba_id'])
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumbs'] = [
            {
                'title': 'Home',
                'url': 'home',
                'activate': None
            },{
                'title': 'Processo',
                'url': '',
                'activate': None
            },{
                'title': 'Calculo',
                'url': '',
                'activate': None
            },{
                'title': 'Verbas',
                'url': '',
                'activate': None
            },{
                'title': 'Detalhes',
                'url': '',
                'activate': 'true'
            }
        ]
        context['title'] = self.get_title()
        context['card_title'] = 'Listagem'
        context['subtitle'] = 'Aqui você tem a lista de todos os calculos detalhados verbas cadastrados.'
        
        return context

djangoapp/apps/clientes/views/listagem.py
import json
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView

from apps.clientes.models import Clientes


class ListagemClientes(ListView):
    template_name='clientes/listagem.html'
    model = Clientes

    def get_breadcrumbs(self):
        return [
            {
                'title': 'Home',
                'url': 'home',
                'activate': None
            },{
                'title': 'Clientes',
                'url': '',
                'activate': None
            },{
                'title': 'Listagem',
                'url': '',
                'activate': 'true'
            }
        ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumbs'] = self.get_breadcrumbs()
        context['title'] = 'Clientes'
        context['card_title'] = 'Listagem'
        context['subtitle'] = 'Aqui você tem a lista de todos os Clientes cadastrados.'
        
        return context

class AutoCompClientes(View):

    def get(self, *args, **kwargs):
        text = self.request.GET['term']
        result = list(Clientes.objects.filter(nome__icontains=text).values_list('nome',flat=True))
        data = json.dumps(result)
        return HttpResponse(data, 'application/json')

djangoapp/templates/calculos/listagem.html
{% extends "genericos/listagem_simples.html" %}
{% load static %}

{% block info %}
	{% if processo %}
	<div class="px-3 pb-3" style="font-size: 15px">
		<table class="table table-striped table-bordered">
			<tr>
				<th class="p-1 px-2">Reclamada</th>
				<th class="p-1 px-2">Reclamante</th>
				<th class="p-1 px-2">Data de Ajuizamento</th>
			</tr>
			<tr>
				<td class="p-1 px-2">{{ processo.reclamada }}</td>
				<td class="p-1 px-2">{{ processo.reclamante }}</td>
				<td class="p-1 px-2">
					<input type="hidden" value='{{ processo.dt_ajuizamento|date:"d/m/Y" }}'>
					{{ processo.dt_ajuizamento|date:"d/m/Y" }}
				</td>
			</th>
		</table>
	</div>
	{% endif %}
{% endblock %}

{% block thead %}
	<tr>
		<th>Nº do Processo</th>
		<th>Id. Calc</th>
		<th>Valor Devido</th>
		<th>Valor Pago</th>
		<th>Valor Calculado</th>
		<th>Valor Corrigido</th>
		<th>Juros</th>
		<th>Total</th>
		<th>Obs.</th>
		<th></th>
	</tr>
{% endblock %}

{% block tbody%}
	{% for item in object_list %}
		<tr>
			<td class="py-1 align-middle" title="{{ item.processo }}">
				<span class="text-truncate tt-table">{{ item.processo }}</span></td>
			<td class="py-1 align-middle">{{ item.id }}</td>
			<td class="py-1 align-middle">{{ item.total_devido|default_if_none:""|floatformat:2 }}</td>
			<td class="py-1 align-middle">{{ item.total_pago|default_if_none:""|floatformat:2 }}</td>
			<td class="py-1 align-middle">{{ item.total_calculado|default_if_none:""|floatformat:2 }}</td>
			<td class="py-1 align-middle">{{ item.total_corrigido|default_if_none:""|floatformat:2 }}</td>
			<td class="py-1 align-middle">{{ item.total_juros|default_if_none:""|floatformat:2 }}</td>
			<td class="py-1 align-middle">{{ item.total|default_if_none:""|floatformat:2 }}</td>
			<td class="py-1 align-middle" title="{{ item.n_arquivo }}">
				<span class="text-truncate tt-table">{{ item.n_arquivo }}<span>
			</td>
			<td class="py-1 align-middle" class="justify-content-md-center" style="display: flex;">
				<a type="button" class="btn btn-outline-info px-1 py-0 mx-1"
					href="{% url 'listagem_verbas' item.id %}"
					data-bs-toggle="tooltip" data-bs-placement="top" title="Ir para Verbas">
					<i class="mdi mdi-arrange-bring-forward" style="font-size: 15px;"></i>
				</a>
				<form action="{% url 'delete_calculos' item.id %}" method="post">
					{% csrf_token %}
					<button type="submit" class="btn btn-outline-danger px-1 py-0 mx-1"
						data-bs-toggle="tooltip" data-bs-placement="top" title="Deletar Calculo">
						<i class="mdi mdi-delete" style="font-size: 15px;"></i>
					</button>
				</form>
			</td>
		</th>
	{% endfor %}
{% endblock %}

djangoapp/templates/calculos/listagem_detalhes.html
{% extends "genericos/listagem_simples.html" %}
{% load static %}
{% block thead %}
	<tr>
		<th>ID</th>
		<th>Dt. Inicio Calc</th>
		<th>Dt. Fim Calc</th>
		<th>Dt. Liquidação</th>
		<th>Dt. Criação</th>
		<th>Obs.</th>
		<th></th>
	</tr>
{% endblock %}

{% block tbody%}
	{% for item in object_list %}
		<tr>
			<td>{{ item.id }}</td>
			<td><input type="hidden" value='{{ item.dt_inicio_calc|date:"Ymd" }}'>{{ item.dt_inicio_calc|date:"d/m/Y" }}</td>
			<td><input type="hidden" value='{{ item.dt_fim_calc|date:"Ymd" }}'>{{ item.dt_fim_calc|date:"d/m/Y" }}</td>
			<td><input type="hidden" value='{{ item.dt_liquidacao|date:"Ymd" }}'>{{ item.dt_liquidacao|date:"d/m/Y" }}</td>
			<td><input type="hidden" value='{{ item.dt_criacao|date:"Ymd" }}'>{{ item.dt_criacao|date:"d/m/Y" }}</td>
			<td><span title="{{ item.n_arquivo }}">{{ item.n_arquivo|truncatechars:20 }}<span></td>
			<td class="text-center">
				<a type="button" class="btn btn-outline-info"
					href="{% url 'listagem_verbas' item.id %}"
					data-bs-toggle="tooltip" data-bs-placement="top" title="Ir para Verbas">
					<i class="mdi mdi-arrange-bring-forward" style="font-size: 20px;"></i>
				</a>
			</td>
		</th>
	{% endfor %}
{% endblock %}

djangoapp/templates/calculos/listagem_verbas.html
{% extends "base/index.html" %}
{% load static %}
{% block css %}
	<link href="{% static '/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css' %}" rel="stylesheet" />
{% endblock %}
{% block container%}
	<!-- ============================================================== -->
	<!-- Container fluid  -->
	<!-- ============================================================== -->
	<div class="container-fluid">
		<!-- ============================================================== -->
		<!-- Start Page Content -->
		<!-- ============================================================== -->
		<div>
			{% if calculo %}
			<div class="px-3 pb-3" style="font-size: 15px">
				<table class="table table-striped table-bordered">
					<tr>
						<th class="p-1 px-2">Valor Devido</th>
						<th class="p-1 px-2">Valor Pago</th>
						<th class="p-1 px-2">Valor Calculado</th>
						<th class="p-1 px-2">Valor Corrigido</th>
						<th class="p-1 px-2">Juros</th>
						<th class="p-1 px-2">Total</th>
						{% if calculo.n_arquivo %}
						<th class="p-1 px-2">Obs.</th>
						{% endif %}
					</tr>
					<tr>
						<td class="py-1">{{ calculo.total_devido|default_if_none:""|floatformat:2 }}</td>
						<td class="py-1">{{ calculo.total_pago|default_if_none:""|floatformat:2 }}</td>
						<td class="py-1">{{ calculo.total_calculado|default_if_none:""|floatformat:2 }}</td>
						<td class="py-1">{{ calculo.total_corrigido|default_if_none:""|floatformat:2 }}</td>
						<td class="py-1">{{ calculo.total_juros|default_if_none:""|floatformat:2 }}</td>
						<td class="py-1">{{ calculo.total|default_if_none:""|floatformat:2 }}</td>
						{% if calculo.n_arquivo %}
						<td class="py-1" title="{{ calculo.n_arquivo }}">
							<span class="text-truncate tt-table" >{{ calculo.n_arquivo }}<span>
						</td>
						{% endif %}
					</th>
				</table>
			</div>
			{% endif %}
		</div>
		<div class="card">
			<div class="card-body">
				<div class="table-responsive">
					<table id="listagem" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Verba</th>
								<th>Valor Devido</th>
								<th>Valor Pago</th>
								<th>Valor Calc.</th>
								<th>Valor Corr.</th>
								<th>Juros</th>
								<th>Total</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							{% for item in object_list %}
								<tr>
									<td class="py-1 align-middle">{{ item.descricao|default_if_none:"" }}</td>
									<td class="py-1 align-middle">{{ item.v_devido|default_if_none:""|floatformat:2 }}</td>
									<td class="py-1 align-middle">{{ item.v_pago|default_if_none:""|floatformat:2 }}</td>
									<td class="py-1 align-middle">{{ item.v_calculado|default_if_none:""|floatformat:2 }}</td>
									<td class="py-1 align-middle">{{ item.v_corrigido|default_if_none:""|floatformat:2 }}</td>
									<td class="py-1 align-middle">{{ item.juros|default_if_none:""|floatformat:2 }}</td>
									<td class="py-1 align-middle">{{ item.total|default_if_none:""|floatformat:2 }}</td>
									<td class="py-1 align-middle justify-content-center" style="display: flex;">
										<a type="button" class="btn btn-outline-info px-1 py-0"
											href="{% url 'listagem_verbas_detalhes' item.id %}"
											data-bs-toggle="tooltip" data-bs-placement="top" title="Ir para Verbas">
											<i class="mdi mdi-arrange-send-backward" style="font-size: 15px;"></i>
										</a>
									</td>
								</th>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<div class='row justify-content-md-center'>
			<div class="card col-md-5 mx-2">
				<div class="card-body">
					<h5>Descrição de Créditos e Descontos do Reclamante</h5>
					<div class="table-responsive">
						<table id="listagem" class="table table-striped table-bordered">
							<thead>
								<tr>
									<th>Descição</th>
									<th>Valor</th>
								</tr>
							</thead>
							<tbody>
								{% for item in calculo.creddesreclamante_set.all %}
									<tr>
										<td class="py-1">{{ item.descricao|default_if_none:"" }}</td>
										<td class="py-1">{{ item.valor|default_if_none:""|floatformat:2 }}</td>
									</th>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>

			<div class="card col-md-5 mx-2">
				<div class="card-body">
					<h5>Descrição de Débitos do Reclamado por Credor</h5>
					<div class="table-responsive">
						<table id="listagem" class="table table-striped table-bordered">
							<thead>
								<tr>
									<th>Descição</th>
									<th>Valor</th>
								</tr>
							</thead>
							<tbody>
								{% for item in calculo.debitosreclamado_set.all %}
									<tr>
										<td class="py-1">{{ item.descricao|default_if_none:"" }}</td>
										<td class="py-1">{{ item.valor|default_if_none:""|floatformat:2 }}</td>
									</th>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<!-- ============================================================== -->
		<!-- End Page Content -->
		<!-- ============================================================== -->
	</div>
	<!-- ============================================================== -->
	<!-- End Container fluid  -->
	<!-- ============================================================== -->
{% endblock %}

{% block js %}
    <!-- this page js -->
	<script src="{% static 'assets/extra-libs/DataTables/datatables.min.js' %}"></script>
	<script src="{% static 'assets/extra-libs/DataTables/custom.js' %}"></script>
    <script>
		$("#listagem").DataTable({
			'language': CUSTOM_DATATABLE
		});
    </script>
{% endblock %}